version: 0.0
os: linux
files:
  - source: ./
    destination: /home/ubuntu/mockany

permissions:
  - object: /
    pattern: "**"
    owner: ubuntu
    group: ubuntu

hooks:
  ApplicationStart:
    - location: scripts/start.sh
      timeout: 10
      runas: ubuntu